# Limita la memoria de Gradle a 2 GB y Metaspace a 512 MB
org.gradle.jvmargs=-Xmx2048m -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m

# Desactiva la ejecución paralela excesiva para no saturar la CPU/RAM
org.gradle.parallel=false
org.gradle.workers.max=2

# Mantén el resto de optimizaciones de caché
org.gradle.caching=true
org.gradle.configuration-cache=true
android.nonTransitiveRClass=true
android.defaults.buildFeatures.resValues=false
android.enableJetifier=false
kotlin.incremental=true